### ISSUE TITLE
When you try to use it with Node 12 mupx deploy fails

### ISSUE THREAD

**Issue by drnachio** [BinPar/bi-mupx#9]
When you try to use a **mupx deploy** on **node 12** (v12.14.0 in my case) it gives you this error:

```terminal
fs.js:27
const { Math, Object } = primordials;
                         ^
ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/usr/local/lib/node_modules/@binpar/mupx/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/usr/local/lib/node_modules/@binpar/mupx/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@binpar/mupx/node_modules/configstore/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
```

We are downgrading node using **nvm** until it is fixed but I will be great to do a fix if it is as easy as it looks like.

**Comment by drnachio** [comment]
It looks that the issue comes from the NPM dependency **archiver**: probably an update will be a fix.
